### PR TITLE
Use exponential backoff when requeueing Done.xml files

### LINKED ISSUE #1603: Submission of "Done" step no longer closes a build
# Bug report

### Expected Behavior

When CTest submits `Done.xml` for a build, that build should be closed so that further submissions refresh it rather than appending.

### Actual Behavior

CTest submits `Done.xml` but the build remains open and further submissions append.

### CDash Version

This problem started on `open.cdash.org` after the recent update.  It is currently running version 3.1.0-442-g6e68ccc9e.

### PR DESCRIPTION
**Pull request by zackgalbreath**
After the recent upgrade of open.cdash.org, we noticed many builds were no longer marked as "Done". This was due to the Done.xml handler exhausting its 5 retries while a single large Test.xml file was in the process of being parsed.

We solve this problem by exponentially backing off the requeueing of Done.xml files to give CDash more time to finish parsing any such large XML files for a given build.

Fixes #1603

This PR also contains a couple other semi-related fixes dealing with parallel parsing of submission files.

### CODE REVIEW

File: config/cdash.php [hunk 1]
```diff
@@ -67,7 +67,9 @@
     'notify_pull_request' => env('NOTIFY_PULL_REQUEST', false),
     'php_exe' => env('PHP_EXE', ''),
     'phpunit_exe' => env('PHPUNIT_EXE', ''),
+    'queue_timeout' => env('QUEUE_TIMEOUT', 2000),
     'remote_workers' => env('REMOTE_WORKERS', false),
+    'retry_base' => env('QUEUE_RETRY_BASE', 5),
```
Comment (williamjallen) [inline config/cdash.php:72]: Should this be added to `.env.example` as well?

**Review by williamjallen — COMMENTED** [review]
These changes seem reasonable to me.  In the future, it might be worthwhile to look into Laravel's [job batching](https://laravel.com/docs/10.x/queues#job-batching) and [job chaining](https://laravel.com/docs/10.x/queues#job-batching) features instead.  Doing so would require a significant refactor of the submission process though.

File: config/cdash.php (hunk 1 above)
Comment (zackgalbreath) [reply config/cdash.php:72]: Unless you feel otherwise, I was inclined to leave it out. For now, it only exists to keep the `donehandler` test from taking a long time to complete.

Comment (williamjallen) [reply config/cdash.php:72]: In my opinion, all of the possible configuration options should be documented in `.env.example` in case someone goes looking for settings to change if they experience issues.  

As of now, `.env.example` is the most complete listing of all of the CDash configuration options.  In the future, perhaps `.env.example` should be a subset of the most common options, with a larger list stored somewhere else.

**Review by williamjallen — APPROVED** [review]
