### PR TITLE
Call cdashmail() from Notification/Email/Mail.php

### LINKED ISSUE #2618: Email notifications failing from workers
CDash v3.6.2

Email notifications are failing to send because they are defaulting to sendmail even though MAIL_MAILER is set to "smtp".

[2024-12-09 18:45:18] production.INFO: Connection to "process /usr/sbin/sendmail -bs" has been closed unexpectedly.  
[2024-12-09 18:45:18] production.INFO: [SENT] EmailMessage titled, 'FAILED (m=1): <redacted>
[2024-12-09 18:46:36] production.INFO: Connection to "process /usr/sbin/sendmail -bs" has been closed unexpectedly.  
[2024-12-09 18:46:36] production.INFO: [SENT] EmailMessage titled, 'FAILED (t=1): <redacted>

Here are the MAIL options I have set:

MAIL_MAILER=smtp
MAIL_HOST=mymailer.domain
MAIL_PORT=25
MAIL_FROM_ADDRESS=<from address>
MAIL_FROM_NAME=<from name>
MAIL_REPLY_ADDRESS=<from address>

Please let me know if I can provide any additional information.

### PR DESCRIPTION
**Pull request by zackgalbreath**
Fixes #2618

### CODE REVIEW

File: app/cdash/include/Messaging/Notification/Email/Mail.php [hunk 1]
```diff
@@ -41,60 +34,9 @@ public function setRecipient($recipient)
...
-        if (!$this->defaultSender) {
-            $this->defaultSender = config('mail.from.address');
-        }
-        return $this->defaultSender;
-    }
-
-    public function getMailer(): Mailer
-    {
-        if (!$this->mailer) {
-            if (config('mail.driver') === 'smtp') {
```
Comment (zackgalbreath) [inline app/cdash/include/Messaging/Notification/Email/Mail.php:55]: For context, here's where the bug actually was. `mail.driver` got renamed to `mail.default` when we upgraded to Laravel 9 in #1282

**Review by williamjallen — APPROVED** [review]
Looks reasonable to me.  It's worth noting that `app/cdash/include/Messaging/Notification/Email/Mail.php` is practically unused at this point.  I'll clean it up in a separate PR as part of a general clean up of the mail/notifications part of the codebase.
